# Generated by Django 4.2.7 on 2025-10-01 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Название может содержать только кириллицу, цифры, пробелы и тире', regex='^[а-яА-ЯёЁ0-9\\s\\-]+$')], verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Название может содержать только кириллицу, цифры, пробелы и тире', regex='^[а-яА-ЯёЁ0-9\\s\\-]+$')], verbose_name='Название'),
        ),
    ]
